services:
  h2:
    image: oscarfonts/h2:latest
    container_name: remessa_h2
    environment:
      H2_OPTIONS: -ifNotExists
    ports:
      - "1521:1521"
      - "81:81"
    restart: always
    networks:
      - backend

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-remessa
    ports:
      - "8080:8080"
    depends_on:
      - h2
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./target:/app/target

networks:
  backend:
    driver: bridge


